name: DevSecOps pipeline (DefectDojo)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  security-events: write

env:
  FAIL_ON_CRITICAL: "true"  

jobs:
  # =========================
  # Stage 1 — Build & push
  # =========================
  build_and_push:
    name: Stage 1 – Build & push image to GHCR
    runs-on: ubuntu-24.04
    outputs:
      image: ${{ steps.meta.outputs.image }}
      tag:   ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

     
      - name: Compute image meta (lowercase)
        id: meta
        shell: bash
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          repo="${GITHUB_REPOSITORY#*/}"
          echo "image=ghcr.io/${owner}/${repo}" >> "$GITHUB_OUTPUT"
          echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}

      - name: Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
            ${{ steps.meta.outputs.image }}:latest

  # ==========================================
  # Stage 2 — SAST + Secrets + Config (SARIF)
  # ==========================================
    # ==========================================
  # Stage 2 — SAST + Secrets + Config (SARIF)
  # ==========================================
  sast_secrets_config:
    name: Stage 2/4 – SAST + Secrets + Config
    runs-on: ubuntu-24.04
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4

      # --- Bandit (Python) -> bandit.sarif ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bandit (SARIF)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          bandit -r . -f sarif -o bandit.sarif || true

      # --- Semgrep -> semgrep.sarif ---
      - name: Semgrep (SARIF)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true
        continue-on-error: true

      - name: Normalize Semgrep SARIF filename
        shell: bash
        run: |
          # semgrep-action может положить results.sarif
          if [ -f results.sarif ] && [ ! -f semgrep.sarif ]; then
            mv results.sarif semgrep.sarif
          fi

      # --- Gitleaks (secrets) -> gitleaks.sarif ---
      - name: Gitleaks (SARIF)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --report-format sarif --report-path gitleaks.sarif --exit-code 0
        continue-on-error: true

      # --- Hadolint (Dockerfile lint) ---
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
        continue-on-error: true

      # --- Trivy image scan -> trivy.sarif ---
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ needs.build_and_push.outputs.image }}:${{ needs.build_and_push.outputs.tag }}
          format: sarif
          output: trivy.sarif
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: 0
        continue-on-error: true

      # --- Debug: показать, какие *.sarif реально есть ---
      - name: Debug SARIF files
        shell: bash
        run: |
          echo "=== LS in workspace ==="
          ls -la
          echo "=== Found SARIF ==="
          ls -la *.sarif || echo "No SARIF files found"

      # --- Upload SARIF (только если файл есть) ---
      - name: Upload Bandit SARIF
        if: always() && hashFiles('bandit.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
          category: bandit

      - name: Upload Semgrep SARIF
        if: always() && hashFiles('semgrep.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep

      - name: Upload Gitleaks SARIF
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks

      - name: Upload Trivy SARIF
        if: always() && hashFiles('trivy.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
          category: trivy


  # ===================================================
  # Stage 3 — DAST (можно оставить как placeholder)
  # ===================================================
  dast:
    name: Stage 3 – DAST (placeholder)
    runs-on: ubuntu-24.04
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4
      - name: DAST placeholder
        run: echo "DAST step can run ZAP here (disabled for Actions runners demo)."

  # =========================
  # Stage 5 — Security Gate
  # =========================
  security_gate:
    name: Stage 5 – Security Gate
    runs-on: ubuntu-24.04
    needs: [build_and_push, sast_secrets_config, dast]
    if: always()
    steps:
      - name: Gate summary
        shell: bash
        run: |
          echo "Security Gate: здесь можно парсить *.sarif и падать по порогу."
          echo "Сейчас пропускаем, чтобы пайплайн не падал на демо."
